### ISSUE TITLE
[Bug][Jenkins] Unable to fetch Jenkins jobs from the folders

### ISSUE THREAD

**Issue by sakshikatariadev** [apache/devlake#5224] opened 2023-05-17 18:55 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am using latest version of DevLake v0.17.0-beta5 and I have tried v0.16.1-beta1 and got same issue in both.

have added a new blueprint for Jenkins and it shows all the Jenkins folder I have but when I click on a folder, it opens a new tab and show the same exact thing as first one.

![image](https://github.com/apache/incubator-devlake/assets/133911099/6c99d840-785f-480e-b90f-e1fdccc8c065)

### What do you expect to happen

It should let us choose jobs from the folder or at least not show the duplicate tabs on each click

### How to reproduce

Make sure you have some folders on Jenkins connected to DevLake.

- Create a blueprint and choose Jenkins
- Select the jobs and click on a folder 
- You will see duplicate tabs opening

### Version

v0.17.0-beta5 and v0.16.1-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment] 2023-05-19 09:16
hi, @sakshikatariadev, thank you for your report.
could you please provide the origin data to me?

**Comment by mintsweet** [comment] 2023-05-22 02:03
> > hi, @sakshikatariadev, thank you for your report. could you please provide the origin data to me?
> 
> I am not sure if I understand the ask here. I have connected the Jenkins server we use in our project.

Could you please check the network in web development, and provide the data to me?

Here

![image](https://github.com/apache/incubator-devlake/assets/37237996/b2961397-b0ab-4f27-b4f5-5d01b8af6b27)

**Comment by xavi-belloso** [comment] 2023-05-22 16:34
Same behavior, I think the problem is that the ALL option is not unchecked, even another folder is selected.
![image](https://github.com/apache/incubator-devlake/assets/36540837/f0221e67-98ce-49a2-ae9c-662366180ebc)

**Comment by xavi-belloso** [comment] 2023-05-22 16:36
Same behavior, I think the problem is that the ALL option is not unchecked, even another folder is selected.
![image](https://github.com/apache/incubator-devlake/assets/36540837/4548c67c-da28-4910-88ef-1562c0d3b934)

**Comment by sakshikatariadev** [comment] 2023-05-22 17:13
Hi @mintsweet Please find HAR file
[localhost_blueprint.zip](https://github.com/apache/incubator-devlake/files/11533929/localhost_blueprint.zip)

**Comment by sakshikatariadev** [comment] 2023-05-22 17:13
@xavi-belloso I do not see ALL option. Which DevLake version are you utilizing?

**Comment by xavi-belloso** [comment] 2023-05-22 17:18
@sakshikatariadev the latest v0.17.0-beta5

**Comment by mintsweet** [comment] 2023-05-23 01:48
hi @sakshikatariadev.

Could you please request the origin Jenkins API and check the response?

`{Jenkins Endpoint}/rest/api/json?tree=jobs[name,jobs]{0,10000}`
`{Jenkins Endpoint}/rest/job/ade/api/json?tree=jobs[name,jobs]{0,10000}`

It seems that these two APIs return the same result, I need to determine if it is a problem with the Jenkins API.

**Comment by sakshikatariadev** [comment] 2023-05-23 03:34
@mintsweet Hi, With version v0.17.0-beta5, I was using {Jenkins Endpoint}/api/json/ and the connection says "online" but it was giving issues for which I created the bug report
Now I tried just the {Jenkins Endpoint} URL and it let's me navigate through each folder. 

These are giving connection issues: 
{Jenkins Endpoint}/rest/api/json?tree=jobs[name,jobs]{0,10000}
{Jenkins Endpoint}/rest/job/ade/api/json?tree=jobs[name,jobs]{0,10000}

What should be the proper URL for Jenkins? 
Also, @xavi-belloso mentioned utilizing the same version but in the screenshot I see an option to select all which I do not see in my UI

**Comment by mintsweet** [comment] 2023-05-23 05:54
hi @sakshikatariadev.

1. You can find the version info on the left side bottom in Config-UI(the selected all button in (https://github.com/mintsweet/incubator-devlake/commit/3749e510c344f14af687e45a9bedc0065ad4ae21).
2. Jenkins URL is your Jenkins instance

**Comment by xavi-belloso** [comment] 2023-05-23 06:36
Hi @mintsweet ,

But I can't uncheck All option, then when I select any folder, shows again the same list. Something doesn't work properly. 

Thanks 😊

**Comment by mintsweet** [comment] 2023-05-23 08:17
hi @xavi-belloso ,

Could you please provide something to me?

![image](https://github.com/apache/incubator-devlake/assets/37237996/84e1cd18-10db-4d5a-826f-8437f05081cb)

1. the network request url.
2. the network response origin data.

**Comment by xavi-belloso** [comment] 2023-05-23 09:43
hi @mintsweet, my colleage @luis-benedicto remove /api/json from the connection url, and now works fine!!!

**Comment by mintsweet** [comment] 2023-05-24 01:43
hi @xavi-belloso, that sounds great.
hi @sakshikatariadev, can you try to change the connection url?

**Comment by hezyin** [comment] 2023-05-25 01:31
@sakshikatariadev @xavi-belloso Thanks for reporting this issue, we've fixed the test connection logic here: https://github.com/apache/incubator-devlake/issues/5272.

**Comment by hezyin** [comment] 2023-05-31 02:23
This issue is caused by an invalid endpoint URL configured. The improvement is tracked here: https://github.com/apache/incubator-devlake/issues/5272. Closing this issue now.

**Closed as completed by hezyin** 2023-05-31 02:23 UTC
Labels: type/bug
