### ISSUE TITLE
[Bug][ZenTao] Status mapping unsuccessful

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#5972] opened 2023-08-29 10:06 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

On the EE front end, the status mapping is configured, and the config interface returns that the configuration is successful, but the status and original_status in the issues table are the same

### What do you expect to happen

Taking 6119 bug as an example, active is mapped to "开发中", then the status of key_id = 6119 in the issues table should be "开发中"
![image](https://github.com/apache/incubator-devlake/assets/142298906/f9a9a446-7c4e-4f77-841c-5193e87bacea)

### How to reproduce

1.  On the EE front end, the status mapping is configured, and the config interface returns
![image](https://github.com/apache/incubator-devlake/assets/142298906/ef44a501-21d3-4552-8dac-8a7feb42dd7d)
2. Finish data collection, view issues table
3. 
![image](https://github.com/apache/incubator-devlake/assets/142298906/cebe62ee-b577-4cee-a7d6-417622c6ba38)
![image](https://github.com/apache/incubator-devlake/assets/142298906/6b038903-e3a7-461c-a562-4bf99b7c44c5)

### Version

v0.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment] 2023-08-29 11:05
@narrowizard please help to solve it

**Comment by narrowizard** [comment] 2023-09-05 03:12
It's not a bug from devlake. Since status mapping works if we only set up zentao plugin.  
Pls close the issue @xiaomingzhang12

**Closed as completed** 2023-09-13 06:48 UTC
Labels: type/bug
