### ISSUE TITLE
[Bug][UI] "RangeError: Maximum call stack size exceeded" when adding a Data Scope

### ISSUE THREAD

**Issue by mbravorus** [apache/devlake#6211] opened 2023-10-10 13:18 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When adding a Data Scope on a Github connection to a Github Enterprise Server v3.8, and clicking on a git org which contains *many* repos (over a thousand), I receive the error "RangeError: Maximum call stack size exceeded". I have tried this with GraphQL on and off, it doesn't matter.

![image](https://github.com/apache/incubator-devlake/assets/593723/6f771057-2a8e-4613-81db-6e64f22d68ed)

### What do you expect to happen

I expect to see a list of the repositories in the right-hand box and be able to select the ones I need

### How to reproduce

Connect to a Github installation (checked only on a server, not entirely sure if Github Cloud behaves the same), ensure it has a git org with more than a thousand repos, and attempt to add a data scope for that org

### Anything else

Happens every time

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mintsweet** [comment] 2023-10-12 03:17
hi @mbravorus , thank you for your feedback.

We have received a lot of feedback about this issue, but have not been able to successfully reproduce it. I will continue to pay attention to this issue. Thank you.

**Comment by mintsweet** [comment] 2023-10-12 03:40
#5680

**Comment by klesh** [comment] 2023-10-12 03:42
Would you mind sharing a screen-recording video for further investigation? Thanks

**Comment by mbravorus** [comment] 2023-10-12 09:40
sure, please find attached

https://github.com/apache/incubator-devlake/assets/593723/9521a57f-46ef-4730-a347-3a3570e03882

**Comment by kirestamenov** [comment] 2024-02-29 08:26
Hello there,
I am experiencing the same problem and I am running v0.21.0-beta4. Seems like that issue is not related to the number of projects in a group. I have two groups with 46 projects each, and one of them I was able to import and the other group I was not. 
Also the issue seems to be with rendering the results, cause if I open the endpoint that it tries to reach, https://devlakeendpooint.net/api/plugins/gitlab/connections/1/remote-scopes?groupId=XX works as expected and I receive the projects in a json format.
Thanks.

**Comment by mintsweet** [comment] 2024-02-29 08:39
hi @kirestamenov, your guess is correct. I need specific data to help me reproduce this issue. Can you provide it?

**Comment by kirestamenov** [comment] 2024-02-29 10:00
hey @mintsweet what kind of data do you need, can you be more specific please? FYI: all repos are part of self-managed gitlab server

**Comment by mintsweet** [comment] 2024-03-01 01:41
Hi @kirestamenov, sorry for not making it clear, I need what the API returns when this error occurs.

![image](https://github.com/apache/incubator-devlake/assets/37237996/27eb90e2-fe5d-4a4a-9a03-0bc34b1b71ed)

**Comment by kirestamenov** [comment] 2024-03-01 11:12
Hey @mintsweet, please find attached the response from the endpoint I mentioned above. I had to mask some of the data
[masked_error_response.json](https://github.com/apache/incubator-devlake/files/14460263/masked_error_response.json)

**Comment by mintsweet** [comment] 2024-03-04 02:40
Hi @kirestamenov, thank you for your data. I'll check it today.

**Comment by Dimatime** [comment] 2024-03-04 21:23
Hello,

I've encountered the same issue as described here. Previously, I was using v0.21.0-beta1. To try and solve the problem, I upgraded to v0.21.0-beta6, but unfortunately, the issue persists. Could anyone provide guidance on whether it's possible to resolve this? The problem doesn't occur in all projects, but so far, I'm unable to determine what might be causing it.

Any insights or suggestions would be greatly appreciated.

Thank you.
[
![Снимок экрана 2024-03-05 в 00 20 05](https://github.com/apache/incubator-devlake/assets/8095103/f39c3786-2147-434d-9f45-c79da33a480e)
](url)

**Comment by mintsweet** [comment] 2024-03-05 07:29
Hi, @kirestamenov, thank you for your data, I'll fix this issue soon.

Hi, @Dimatime, this issue will be fixed soon, please wait patiently.

**Closed as completed** 2024-03-05 07:43 UTC
Labels: type/bug

**Comment by Dimatime** [comment] 2024-03-05 07:56
@mintsweet Thank you for your prompt response and quick attention to our request! We greatly appreciate your focus on our inquiry. We are eagerly looking forward to the release. Thank you for your efforts and support!

**Comment by kirestamenov** [comment] 2024-03-11 09:38
hey @mintsweet,

we just deployed v0.21.0-beta7 and everything works as expected.
Thanks a lot for immediate action on this. Much appreciated.
Thanks a bunch
