### ISSUE TITLE
[Bug][AzureDevOps] Production pattern don't work

### ISSUE THREAD

**Issue by ghost** [apache/devlake#6266] opened 2023-10-17 20:45 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Azure DevOps Connections created with scope configuration production pattern don't get marked as PRODUCTION deployments.

Azure DevOps Pipeline name: test-ci-prod
Scope configuration deployment pattern : test-ci
Scope configuration production pattern: prod

The deployments identified for test-ci-prod Pipeline are being marked as TESTING.

### What do you expect to happen

The deployments should be marked as PRODUCTION 

### How to reproduce

Steps to reproduce
  1. Create a new Azure DevOps Repository 
  1. Create a new Azure DevOps Pipeline named test-ci-prod
  1. Run the created pipeline at least 3 times
  1. Configure a new Azure DevOps Connection 
  1. Add  a new Data Scope referencing the created repository
  1. Add a new Scope Configuration with deployment pattern like 'test-ci' and production pattern like 'prod'
  1. Collect data
  1. Observe that none of the deployments are marked as PRODUCTION despite the production pattern correctly configured

### Version

v0.18.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rodrigocmn** [comment] 2023-11-06 08:20
I have the same problem.

**Comment by rodrigocmn** [comment] 2023-11-06 12:37
Quick update... After doing some more tests, I've noticed that the regex configuration for transformation is case-sensitive. Therefore, the pipeline or job name must contain deploy and prod in lower case.

It would be great if the regex could be changed to case-insensitive.

**Comment by Startrekzky** [comment] 2023-11-07 03:17
Do you think we should add the default `(?i)` back to every regex configuration's placeholder in the Scope Config? @d4x1 @mintsweet 
![image](https://github.com/apache/incubator-devlake/assets/14050754/fa93909d-2352-4d3f-ae36-59a663d18e95)

**Comment by d4x1** [comment] 2023-11-08 10:20
> Do you think we should add the default `(?i)` back to every regex configuration's placeholder in the Scope Config? @d4x1 @mintsweet ![image](https://user-images.githubusercontent.com/14050754/280909099-fa93909d-2352-4d3f-ae36-59a663d18e95.png)

I think we should keep them uniformed.

**Comment by Startrekzky** [comment] 2024-01-19 12:20
Closed as it is not a bug. Feel free to reopen it if it still exists.

**Closed as completed by Startrekzky** 2024-01-19 12:20 UTC
Labels: type/bug
