### ISSUE TITLE
[Bug][Azure DevOps] SQL Sha Merge Commit cannot be null

### ISSUE THREAD

**Issue by andremattosferraz** [apache/devlake#5298] opened 2023-05-26 14:10 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

<img width="1395" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/6d2dd124-1639-4935-b6d0-c5e62b8a0166">

### What do you expect to happen

SHA MERGE COMMIT can be null on the database.

### How to reproduce

Run DevOps integration

### Version

v0.17.0-beta7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by andremattosferraz** [comment] 2023-05-26 14:11
Log file
[task-160-2-1-azuredevops.log](https://github.com/apache/incubator-devlake/files/11576027/task-160-2-1-azuredevops.log)

**Comment by andremattosferraz** [comment] 2023-05-26 21:07
Is still occurring in the beta8 release.

I changed the column to accept null and now pop another error:
[task-174-2-1-azuredevops.log](https://github.com/apache/incubator-devlake/files/11579941/task-174-2-1-azuredevops.log)

<img width="1440" alt="image" src="https://github.com/apache/incubator-devlake/assets/133804167/615e5940-d779-4f3c-8110-eed0c5a60a07">

**Comment by klesh** [comment] 2023-05-28 03:13
@CamilleTeruel please kindly take a look, thanks

**Comment by CamilleTeruel** [comment] 2023-05-29 15:43
Sorry @andremattosferraz, I tried to solve your issue but could not reproduce the error.
I don't understand how the row `merge_commit_sha` ended up with a non null constraint in your db.
As for the second error, this PR fixes it: https://github.com/apache/incubator-devlake/pull/5310

**Comment by andremattosferraz** [comment] 2023-05-29 15:49
@CamilleTeruel do you use migrations to update the DB automatically? If yes, each new deploy I should run anything? Or I should update the database manually?

**Comment by CamilleTeruel** [comment] 2023-05-29 16:33
> @CamilleTeruel do you use migrations to update the DB automatically? If yes, each new deploy I should run anything? Or I should update the database manually?

If migrations are needed you'd be prompted to run them by the web UI. If you don't use the web UI, you can trigger it manually with a GET request to `/proceed-db-migration`.
But this is not a migration issue, this column has been marked nullable (or `Optional` on python code) since it was merged. It could be a bug with a specific version of the ORM (`sqlmodel`) but then why would it not affect other nullable columns?

**Comment by andremattosferraz** [comment] 2023-05-29 16:47
Strange, because my DB was a required field.

**Comment by klesh** [comment] 2023-05-30 02:59
@andremattosferraz What kind of db are you using? Can you share the detail of the database server.

**Comment by CamilleTeruel** [comment] 2023-05-30 11:51
@KlemenDanfoss has the same issue (see comment in #5275). You can set this column as nullable in your DB: `ALTER TABLE _tool_azuredevops_gitpullrequests MODIFY merge_commit_sha varchar(255) null`. The problem is that we don't know how this column ended up `NON NULL` in the first place. 
So any insight about how to reproduce is welcomed.

@andremattosferraz Did the column became required again after you changed it?

**Comment by andremattosferraz** [comment] 2023-05-30 12:53
The database is MySQL and the attribute still null after I changed it manually. I force to run migrations using the GET request /proceed-db-migration to check if it is back to not null. But no...

**Comment by KlemenDanfoss** [comment] 2023-05-31 12:37
What I did:

1.)
`ALTER TABLE _tool_azuredevops_gitpullrequests MODIFY merge_commit_sha varchar(255) null;`
ran again

2.)
Destroyed everything (including db)
ran again

Result in both cases:

```
ERROR: Operational error (raised as a result of query-invoked autoflush; consider using a session.no_autoflush block if his flush is occurring prematurely) | (mysqldb.operationalerror) (1048, "Coumne 'result' cannot be null") | sql INSERT INTO _tool_azuredevops_builds (...)
```

**Comment by alexvaccaro** [comment] 2023-06-01 09:56
I am getting exact same error. 

I had previously installed v0.17.0-beta4 from scratch, I then tried to setup a project and blueprint but had to abort because of #5151 
Today I upgraded to v0.17.0-beta8, launched the web ui, run the migration and when I tried to run the blueprint got the same exact issue as reported by here.

**Comment by CamilleTeruel** [comment] 2023-06-01 14:20
This bug happens if you have run the azure devops plugin before v0.17.0-beta6.
I'm sorry but contrary to what I said previously, this field was not marked optional before beta6.

If you have this issue, execute the following on your db instance:
`ALTER TABLE _tool_azuredevops_gitpullrequests MODIFY merge_commit_sha varchar(255) null;`

We can add a migration script. IMO, it is not worth it as it affect only DBs that ran under beta versions. I vote for closing this issue.

@klesh @hezyin What do you think, do we close issue or add missing migration?

**Comment by andremattosferraz** [comment] 2023-06-01 14:45
Make sense @CamilleTeruel. I think the first deployment was using 16... I started to use 17 about 3 weeks ago.
+1 to close

**Comment by alexvaccaro** [comment] 2023-06-01 17:17
I delete the containers and volumes and did a fresh installation of beta8 and now I get this slightly different error:

`ERROR: Operational error (raised as a result of query-invoked autoflush; consider using a session.no_autoflush block if his flush is occurring prematurely) | (mysqldb.operationalerror) (1048, "Column 'result' cannot be null") | sql INSERT INTO _tool_azuredevops_builds (...)`

**Comment by CamilleTeruel** [comment] 2023-06-01 19:36
> Does this need to be raised as a separate bug?

It is solved in https://github.com/apache/incubator-devlake/issues/5336. Will be in next beta.

**Comment by CamilleTeruel** [comment] 2023-06-06 14:11
> @CamilleTeruel in beta10 is still with error. But now: build not found.

Please open a new issue with information related to this build 4863 such as:
- does it exists in your azure project?
- is there anything special about this build?
- is it returned by `_apis/build/builds`? (can be in a later page)
- ...

**Closed as completed by CamilleTeruel** 2023-06-06 14:11 UTC
Labels: type/bug

**Comment by andremattosferraz** [comment] 2023-06-06 14:28
@CamilleTeruel #5298

**Comment by KlemenDanfoss** [comment] 2023-06-09 09:04
> I delete the containers and volumes and did a fresh installation of beta8 and now I get this slightly different error:
> 
> `ERROR: Operational error (raised as a result of query-invoked autoflush; consider using a session.no_autoflush block if his flush is occurring prematurely) | (mysqldb.operationalerror) (1048, "Column 'result' cannot be null") | sql INSERT INTO _tool_azuredevops_builds (...)`
> 
> Does this need to be raised as a separate bug?

@CamilleTeruel I still get this error in beta10.

**Comment by KlemenDanfoss** [comment] 2023-06-16 12:39
@CamilleTeruel , great, it works!
