### ISSUE TITLE
[Bug][Azure Devops] 500 on adding additional repository

### ISSUE THREAD

**Issue by klemen-df** [apache/devlake#6477] opened 2023-11-16 07:31 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I have a working Azure Devops project with added one (1) repository.

I tried to add an additional repository. I tried to 'Add Data Scope' and then on the screen where the organizations should be loaded nothing happens.

In the F12 I get:

![image](https://github.com/apache/incubator-devlake/assets/93664973/ed87f1bb-0eba-45bb-b071-3c0460cf7203)

and in the backend:

```
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=info msg="DEBUG: Starting new HTTPS connection (1): dev.azure.com:443"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=info msg="DEBUG: https://dev.azure.com:443 \"GET /6k0HcPP7LskzUitU6GJx+g==/_apis/projects?api-version=7.0 HTTP/1.1\" 404 0"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="Traceback (most recent call last):"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="  File \"/app/python/plugins/azuredevops/azuredevops/main.py\", line 156, in <module>"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="    AzureDevOpsPlugin.start()"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="  File \"/app/python/pydevlake/pydevlake/plugin.py\", line 253, in start"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="    fire.Fire(PluginCommands(plugin))"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="  File \"/app/.cache/pypoetry/virtualenvs/azuredevops-ANnMAkq9-py3.9/lib/python3.9/site-packages/fire/core.py\", line 141, in Fire"
2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=error msg="    component_trace = _Fire(component, args, parsed_flag_args, context, name)"
```

### What do you expect to happen

I should see a list of successfuly loaded organizations and then proceed to the screen where I select a repository.

### How to reproduce

Setup an azure devops project, using azure repos repository
Try to add an additional repository

### Anything else

Same thing happens if I use a different user (and PAT), create new project, new connection...

### Version

v0.19.1-beta1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KlemenDanfoss** [comment] 2023-11-22 08:40
Anything new here?

**Comment by d4x1** [comment] 2023-11-22 09:05
@KlemenDanfoss  
From your logs, I find something like `2023-11-16T08:27:24+01:00 time="2023-11-16 07:27:24" level=info msg="DEBUG: https://dev.azure.com:443 \"GET /6k0HcPP7LskzUitU6GJx+g==/_apis/projects?api-version=7.0 HTTP/1.1\" 404 0"
`

Can you try another Azure Devops repo?
And, we have do some fix about Azure Devops on v0.20,  you can use https://github.com/apache/incubator-devlake/releases/tag/v0.20.0-beta2 if possible.

**Comment by KlemenDanfoss** [comment] 2023-11-22 09:21
Every other repo is the same. Upgrade to v0.20-beta2 didn't help.

**Comment by d4x1** [comment] 2023-11-22 09:33
@KlemenDanfoss Can you paste the response of API `/api/plugins/auzredevops/connections/1/remote-scope`?

**Comment by KlemenDanfoss** [comment] 2023-11-22 09:40
@d4x1 

```
time="2023-11-22 09:16:33" level=info msg="endpoint GET /plugins/azuredevops/connections/:connectionId/remote-scopes github.com/apache/incubator-devlake/server/api.handlePluginCall.func1 7"
time="2023-11-22 09:16:33" level=info msg="endpoint GET /plugins/azuredevops/connections/:connectionId/search-remote-scopes github.com/apache/incubator-devlake/server/api.handlePluginCall.func1 7"
time="2023-11-22 09:20:16" level=info msg="path /plugins/azuredevops/connections/2/remote-scopes will continue"
[GIN] 2023/11/22 - 09:20:22 | 200 |  6.714491075s |      10.0.172.3 | GET      "/plugins/azuredevops/connections/2/remote-scopes"
time="2023-11-22 09:20:24" level=info msg="path /plugins/azuredevops/connections/2/remote-scopes will continue"
[GIN] 2023/11/22 - 09:20:27 | 200 |  3.051660152s |      10.0.172.3 | GET      "/plugins/azuredevops/connections/2/remote-scopes?groupId=organization%2FProject"
```

**Comment by d4x1** [comment] 2023-11-22 09:43
I mean the response that your browser get(F12, Network tab).

**Comment by KlemenDanfoss** [comment] 2023-11-22 09:45
Hi,

https://[url/api/plugins/azuredevops/connections/{1,2}/remote-scope](https://url/api/plugins/azuredevops/connections/{1,2}/remote-scope)

Returns 404.

https://[url/api/plugins/azuredevops/connections/{1,2}](https://url/api/plugins/azuredevops/connections/{1,2}
)

Returns the right organization.

**Comment by d4x1** [comment] 2023-11-22 10:05
@KlemenDanfoss  
Show me the response of the api(I think it is `/api/plugins/azuredevops/connections/1/remote-scope`) that returns errors. 
This screenshot may help:
<img width="1380" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/dd2eccdb-8fc5-47f5-a8cd-cb17d99fa20a">

BTW, @keon94  Can you have a look at this issue?

**Comment by KlemenDanfoss** [comment] 2023-11-22 10:11
@d4x1 , like I said - 404

![image](https://github.com/apache/incubator-devlake/assets/93664973/53f5c8f4-7d2c-4d81-83ca-bb322193e4cb)

**Comment by klesh** [comment] 2023-11-23 03:58
@mintsweet Looks like the trailing `s` is missing

**Comment by d4x1** [comment] 2023-11-23 05:45
> @d4x1 Looks like the trailing `s` is missing

It's my mistake. But I don't think missing `s` is this issue's root cause, it's shown the backend returns 500 error.

**Comment by klesh** [comment] 2023-11-23 06:06
Can you share the related logs of the `devlake` container when requesting `/remote-scopes `? thanks.

**Comment by klesh** [comment] 2023-11-23 08:23
The `org` name seems off.
@keon94 , what do you think?

**Comment by keon94** [comment] 2023-11-25 05:53
Yeah. The culprit is obviously the "6k0HcPP7LskzUitU6GJx+g==" string. My suspicion is that perhaps this field is encrypted in the database and it's not getting decrypted [here](https://github.com/apache/incubator-devlake/blob/198665326ed1ee14d1539461747947aae2a37175/backend/server/services/remote/plugin/remote_scope_api.go#L48) for some reason.
@KlemenDanfoss could you check your database azure connection table and see if the org field has that string?

**Comment by klesh** [comment] 2023-11-27 02:58
@keon94 Interesting, why does the `org` name need to be encrypted? It doesn't seem sensitive to me.

**Comment by keon94** [comment] 2023-11-27 03:18
It shouldn't be the case, although prior to https://github.com/apache/incubator-devlake/pull/5286 we used to encrypt all fields. Now it should just be the token that is encrypted.

**Comment by klesh** [comment] 2023-11-27 03:32
@keon94 Oh, sounds like a migration problem to me, maybe the connection was created before #5286?
@KlemenDanfoss Can you try editing the connection and re-enter the `org` name and see if the problem persists?

**Comment by KlemenDanfoss** [comment] 2023-11-27 08:04
> @keon94 Oh, sounds like a migration problem to me, maybe the connection was created before #5286? @KlemenDanfoss Can you try editing the connection and re-enter the `org` name and see if the problem persists?

@klesh , same.

**Comment by KlemenDanfoss** [comment] 2023-12-19 11:42
@klesh closing this - the issue was that WAF (web application firewall) was blocking some requests.

**Closed as completed by KlemenDanfoss** 2023-12-19 11:42 UTC
Labels: type/bug

**Comment by klesh** [comment] 2023-12-20 09:04
glad it works
