### ISSUE TITLE
[Bug][Azure DevOps Go] Add new scope config error

### ISSUE THREAD

**Issue by ArtRout1313** [apache/devlake#7448] opened 2024-05-09 18:17 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

For new a project with a new 'Azure DevOps Go' connection, try to add a new Scope Config and get an error page:

<img width="1327" alt="Screenshot 2024-05-09 at 19 51 59" src="https://github.com/apache/incubator-devlake/assets/141954670/e3c45357-39e4-4e46-9969-777ea7d2576d">

<img width="1275" alt="Screenshot 2024-05-09 at 19 51 40" src="https://github.com/apache/incubator-devlake/assets/141954670/41b8257b-01a7-40be-8143-ef0f3147b3d3">

### What do you expect to happen

Expect to see the 'Add Scope Config' popup window

### How to reproduce

1. Create a new project
2. Create a new Azure DevOps Go connection
3. Test connection
4. Select repos from the connection
5. Open Edit Scope Config Page
6. Push the 'Associate Scope Config' link or button
7. Push the 'Add New Scope Config' button
8. Got an error

### Version

v1.0.0-beta1@60faf14

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mr-ks** [comment] 2024-05-09 19:11
Thanks for reporting, I'll take a look at it.

**Comment by mr-ks** [comment] 2024-05-11 18:26
The problem you are encountering is due to a missing configuration value. The frontend is failing because it cannot read the [transformation documentation](https://github.com/apache/incubator-devlake/blob/60faf149b837283ed2a2bed993c4aa24529fa3b3/config-ui/src/release/stable.ts). The problem is fixed with this commit [[2bb8267](https://github.com/apache/incubator-devlake/blob/2bb82679fd65a810e0d16e360d1c5fe4d24e28fd/config-ui/src/release/stable.ts#L37)](https://github.com/apache/incubator-devlake/blob/2bb82679fd65a810e0d16e360d1c5fe4d24e28fd/config-ui/src/release/stable.ts#L33-L39)

**Comment by ArtRout1313** [comment] 2024-05-13 11:10
@mr-ks - Thank you

**Closed as completed** 2024-05-13 11:09 UTC
Labels: type/bug
